[program:aeps-workers]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/aeps/artisan queue:work redis --sleep=3 --tries=3 --timeout=90
autostart=true
autorestart=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/aeps/worker.log
stopwaitsecs=3600
